 @@ hightlight id_;_Browser("Privileged Account Management").Page("Privileged Account Management").Image("ctl00$MainContent$imgbtnLogin")_;_script infofile_;_ZIP::ssf6.xml_;_
Browser("Privileged Account Management").Page("Privileged Account Management").WebEdit("ctl00$MainContent$txtusername").Set "Milind." @@ hightlight id_;_Browser("Privileged Account Management").Page("Privileged Account Management").WebEdit("ctl00$MainContent$txtusername")_;_script infofile_;_ZIP::ssf7.xml_;_
Browser("Privileged Account Management").Page("Privileged Account Management").WebEdit("ctl00$MainContent$txtusername").Set "Milind.Nikam" @@ hightlight id_;_Browser("Privileged Account Management").Page("Privileged Account Management").WebEdit("ctl00$MainContent$txtusername")_;_script infofile_;_ZIP::ssf8.xml_;_
Browser("Privileged Account Management").Page("Privileged Account Management").WebList("WebElement").Click @@ hightlight id_;_Browser("Privileged Account Management").Page("Privileged Account Management").WebList("WebElement")_;_script infofile_;_ZIP::ssf9.xml_;_
Browser("Privileged Account Management").Page("Privileged Account Management").WebEdit("ctl00$MainContent$txtpassword").SetSecure "5d835c9e1a0c34605eee668f78c4603427c07c4b74ac" @@ hightlight id_;_Browser("Privileged Account Management").Page("Privileged Account Management").WebEdit("ctl00$MainContent$txtpassword")_;_script infofile_;_ZIP::ssf10.xml_;_
Browser("Privileged Account Management").Page("Privileged Account Management").WebTree("select2-ctl00_MainContent_ddld").Select "ARCOSAUTH" @@ hightlight id_;_Browser("Privileged Account Management").Page("Privileged Account Management").WebTree("select2-ctl00 MainContent ddld")_;_script infofile_;_ZIP::ssf11.xml_;_
Browser("Privileged Account Management").Page("Privileged Account Management").Image("ctl00$MainContent$imgbtnLogin").Click 20,22 @@ hightlight id_;_Browser("Privileged Account Management").Page("Privileged Account Management").Image("ctl00$MainContent$imgbtnLogin")_;_script infofile_;_ZIP::ssf12.xml_;_
Browser("Privileged Account Management").Page("Privileged Account Management_2").Sync
Browser("Privileged Account Management").CloseAllTabs @@ hightlight id_;_1771252_;_script infofile_;_ZIP::ssf14.xml_;_
